name: TypeScript CI checks (build, test, lint, formatting)
on: [pull_request]
jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: run all the things
        run: cd ./typescript/ && npm run all
